# Autogenerated wrapper script for HPTT_jll for aarch64-apple-darwin
export libhptt

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("HPTT")
JLLWrappers.@declare_library_product(libhptt, "@rpath/libhptt.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libhptt,
        "lib/libhptt.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
